/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package DictionaryBuilder;

import java.io.FileNotFoundException;

import DictionaryBuilder.Dictionary.DictionaryBuilder;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        // try(ContentReader reader = new ContentReader(new FileInputStream(new File("R:/Development/DictionaryBuilder/app/input/TheDarknessThatComesBeforeGlossary.txt")))){
        //     Content.createContentFile("output/", reader.readContent());
        // } catch(Exception e){
        //     e.printStackTrace();
        // }
        try {
            DictionaryBuilder builder = new DictionaryBuilder("output/")
                .cover("The Second Apocalypse", "Andrew Turner")
                .content("R:/Development/DictionaryBuilder/app/input/TheDarknessThatComesBeforeGlossary.txt");
            builder.build();
        } catch (FileNotFoundException e) {
            e.printStackTrace();
        }
    }
}
