/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package DictionaryBuilder;

import java.io.File;
import java.io.FileInputStream;
import java.util.Scanner;

import util.ContentReader;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        // try(ContentReader reader = new ContentReader(new FileInputStream(new File("R:/Development/DictionaryBuilder/app/input/TheDarknessThatComesBeforeGlossary.txt")))){
        //     Content.createContentFile("output/", reader.readContent());
        // } catch(Exception e){
        //     e.printStackTrace();
        // }
        Scanner scanner = new Scanner(System.in);
        System.out.println("Content file: ");
        String path = scanner.nextLine();
        System.out.println(path);
    }
}
