/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package app;

import java.io.IOException;

import dictionary.Dictionary.DictionaryBuilder;

public class App {

    public static void main(String[] args) {
        
        try {
            DictionaryBuilder builder = new DictionaryBuilder("output/")
                .cover("The Second Apocalypse", "Andrew Turner")
                .content("R:/Development/DictionaryBuilder/app/input/TheDarknessThatComesBeforeGlossary.txt")
                .copyright();
            builder.build();
        } catch (IOException e) {
            e.printStackTrace();
        }
    }
}
