/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package app

import dictionary.Dictionary.DictionaryBuilder
import java.io.IOException

object App {
    @JvmStatic
    fun main(args: Array<String>) {
        try {
            val builder = DictionaryBuilder("output/")
                .cover("The Aspect Emperor Encyclopedic Glossary", "Andrew Turner")
                .content("R:/Development/DictionaryBuilder/app/input/aspectEmperorGlossary.txt")
                .copyright()
            builder.build()
        } catch (e: IOException) {
            e.printStackTrace()
        }
    }
}